# Settings for the app
app:
  # HTML Title
  title: Boro Taxi
  # Header name
  name: _(Where do you want Boro Taxi stands?)
  # Meta description that will show up in Google search results
  meta_description: "_(The Taxi and Limousine Commission wants to know, where do you want Boro Taxi stands?)"

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 40.7
      lng: -73.9
    zoom: 11
    minZoom: 10
    maxZoom: 17
  base_layer:
    # url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
    url: http://b.tile.stamen.com/toner-lite/{z}/{x}/{y}.png
    attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
  layers: []

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  borotaxistand:
    default: hailman-puck
    focused: hailman-marker
    label: _(Boro Taxi Stand)

# Defines place icons. See http://leaflet.cloudmade.com/reference.html#icon
# for documention of each property. Any omitted property will be undefined.
place_type_icons:
  hailman-puck:
    iconUrl: /static/css/images/hailman-puck-26x26.png
    iconSize:
      width: 26
      height: 26
    iconAnchor:
      x: 13
      y: 13
  hailman-marker:
    iconUrl: /static/css/images/hailman-marker-27x44.png
    shadowUrl: /static/css/images/marker-shadow-40x40.png
    iconSize:
      width: 27
      height: 44
    iconAnchor:
      x: 14
      y: 44
    shadowSize:
      width: 40
      height: 40
    shadowAnchor:
      x: 7
      y: 40

activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Suggest a Location)
  action_text: _(suggested)
  title: _(Suggest a Location...)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)
  items:
    - type: hidden
      name: location_type
      attrs:
        - key: value
          value: borotaxistand
    - prompt: _(Why do you want a Boro Taxi stand here?)
      type: textarea
      name: name
      attrs:
        - key: placeholder
          value: _(This is a good location because...)

    - prompt: _(Early Morning)
      type: checkbox
      name: early
      attrs:
        - key: value
          value: _(early)
    - prompt: _(Midday)
      type: checkbox
      name: midday
      attrs:
        - key: value
          value: _(midday)
    - prompt: _(Evening)
      type: checkbox
      name: evening
      attrs:
        - key: value
          value: _(evening)
    - prompt: _(Late Night)
      type: checkbox
      name: late
      attrs:
        - key: value
          value: _(late)

    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
    - prompt: _(Your Name)
      type: text
      name: submitter_name

    - prompt: _(Early Morning)
      type: checkbox
      name: early
      attrs:
        - key: value
          value: _(early)
    - prompt: _(Midday)
      type: checkbox
      name: midday
      attrs:
        - key: value
          value: _(midday)
    - prompt: _(Evening)
      type: checkbox
      name: evening
      attrs:
        - key: value
          value: _(evening)
    - prompt: _(Late Night)
      type: checkbox
      name: late
      attrs:
        - key: value
          value: _(late)

support:
  submission_type: support
  submit_btn_text: _(I'd use this!)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true
